[package]
name = "interpreter"
version = "0.1.0"
edition = "2024"

[dependencies]
compiler_lib = { path = "../compiler_lib" }
escape-bytes = "0.1.1"
im-rc = "15.1"
indicatif = "0.18"
num-bigint = "0.4"
num = "0.4"
rustc-hash = "2.1"